<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AIHelper</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="assets\emoji_tab_icon.png" />
    <None Remove="assets\emoji\21.png" />
    <None Remove="assets\emoji\20.png" />
    <None Remove="assets\emoji\23.png" />
    <None Remove="assets\emoji\22.png" />
    <None Remove="assets\emoji\25.png" />
    <None Remove="assets\emoji\24.png" />
    <None Remove="assets\emoji\27.png" />
    <None Remove="assets\emoji\26.png" />
    <None Remove="assets\emoji\29.png" />
    <None Remove="assets\emoji\28.png" />
    <None Remove="assets\emoji\03.png" />
    <None Remove="assets\emoji\02.png" />
    <None Remove="assets\emoji\01.png" />
    <None Remove="assets\emoji\07.png" />
    <None Remove="assets\emoji\06.png" />
    <None Remove="assets\emoji\05.png" />
    <None Remove="assets\emoji\04.png" />
    <None Remove="assets\emoji\09.png" />
    <None Remove="assets\emoji\08.png" />
    <None Remove="assets\emoji\31.png" />
    <None Remove="assets\emoji\33.png" />
    <None Remove="assets\emoji\30.png" />
    <None Remove="assets\emoji\35.png" />
    <None Remove="assets\emoji\32.png" />
    <None Remove="assets\emoji\37.png" />
    <None Remove="assets\emoji\34.png" />
    <None Remove="assets\emoji\39.png" />
    <None Remove="assets\emoji\36.png" />
    <None Remove="assets\emoji\38.png" />
    <None Remove="assets\emoji\13.png" />
    <None Remove="assets\emoji\11.png" />
    <None Remove="assets\emoji\12.png" />
    <None Remove="assets\emoji\17.png" />
    <None Remove="assets\emoji\10.png" />
    <None Remove="assets\emoji\15.png" />
    <None Remove="assets\emoji\16.png" />
    <None Remove="assets\emoji\14.png" />
    <None Remove="assets\emoji\19.png" />
    <None Remove="assets\emoji\18.png" />
    <None Remove="assets\emoji\47.png" />
    <None Remove="assets\emoji\46.png" />
    <None Remove="assets\emoji\45.png" />
    <None Remove="assets\emoji\44.png" />
    <None Remove="assets\emoji\43.png" />
    <None Remove="assets\emoji\42.png" />
    <None Remove="assets\emoji\41.png" />
    <None Remove="assets\emoji\40.png" />
    <None Remove="views\wencaiwindow.baml" />
    <None Remove="assets\data.png" />
    <None Remove="assets\face\17.png" />
    <None Remove="assets\face\16.png" />
    <None Remove="assets\face\15.png" />
    <None Remove="assets\face\14.png" />
    <None Remove="assets\face\13.png" />
    <None Remove="assets\face\12.png" />
    <None Remove="assets\face\11.png" />
    <None Remove="assets\face\10.png" />
    <None Remove="assets\face\19.png" />
    <None Remove="assets\face\18.png" />
    <None Remove="assets\face\25.png" />
    <None Remove="assets\face\24.png" />
    <None Remove="assets\face\21.png" />
    <None Remove="assets\face\23.png" />
    <None Remove="assets\face\20.png" />
    <None Remove="assets\face\22.png" />
    <None Remove="assets\face\07.png" />
    <None Remove="assets\face\05.png" />
    <None Remove="assets\face\06.png" />
    <None Remove="assets\face\03.png" />
    <None Remove="assets\face\04.png" />
    <None Remove="assets\face\01.png" />
    <None Remove="assets\face\02.png" />
    <None Remove="assets\face\09.png" />
    <None Remove="assets\face\08.png" />
    <None Remove="assets\app.ico" />
    <None Remove="views\chartwindow.baml" />
    <None Remove="views\exportcontrol.baml" />
    <None Remove="views\livechartwindow.baml" />
    <None Remove="views\stockview.baml" />
    <None Remove="tv.js" />
    <None Remove="views\importexportwindow.baml" />
    <None Remove="views\positionwindow.baml" />
    <None Remove="mainwindow.baml" />
    <None Remove="views\proxywindow.baml" />
    <None Remove="assets\emoji.png" />
    <None Remove="views\sparrowwindow.baml" />
    <None Remove="views\turtlewindowdc.baml" />
    <None Remove="assets\pic.png" />
    <None Remove="views\chatview.baml" />
    <None Remove="views\sparrowwindowdc.baml" />
    <None Remove="views\loginwindow.baml" />
    <None Remove="app.baml" />
    <None Remove="views\imageviewerwindow.baml" />
    <Resource Include="assets\emoji_tab_icon.png" />
    <Resource Include="assets\emoji\21.png" />
    <Resource Include="assets\emoji\20.png" />
    <Resource Include="assets\emoji\23.png" />
    <Resource Include="assets\emoji\22.png" />
    <Resource Include="assets\emoji\25.png" />
    <Resource Include="assets\emoji\24.png" />
    <Resource Include="assets\emoji\27.png" />
    <Resource Include="assets\emoji\26.png" />
    <Resource Include="assets\emoji\29.png" />
    <Resource Include="assets\emoji\28.png" />
    <Resource Include="assets\emoji\03.png" />
    <Resource Include="assets\emoji\02.png" />
    <Resource Include="assets\emoji\01.png" />
    <Resource Include="assets\emoji\07.png" />
    <Resource Include="assets\emoji\06.png" />
    <Resource Include="assets\emoji\05.png" />
    <Resource Include="assets\emoji\04.png" />
    <Resource Include="assets\emoji\09.png" />
    <Resource Include="assets\emoji\08.png" />
    <Resource Include="assets\emoji\31.png" />
    <Resource Include="assets\emoji\33.png" />
    <Resource Include="assets\emoji\30.png" />
    <Resource Include="assets\emoji\35.png" />
    <Resource Include="assets\emoji\32.png" />
    <Resource Include="assets\emoji\37.png" />
    <Resource Include="assets\emoji\34.png" />
    <Resource Include="assets\emoji\39.png" />
    <Resource Include="assets\emoji\36.png" />
    <Resource Include="assets\emoji\38.png" />
    <Resource Include="assets\emoji\13.png" />
    <Resource Include="assets\emoji\11.png" />
    <Resource Include="assets\emoji\12.png" />
    <Resource Include="assets\emoji\17.png" />
    <Resource Include="assets\emoji\10.png" />
    <Resource Include="assets\emoji\15.png" />
    <Resource Include="assets\emoji\16.png" />
    <Resource Include="assets\emoji\14.png" />
    <Resource Include="assets\emoji\19.png" />
    <Resource Include="assets\emoji\18.png" />
    <Resource Include="assets\emoji\47.png" />
    <Resource Include="assets\emoji\46.png" />
    <Resource Include="assets\emoji\45.png" />
    <Resource Include="assets\emoji\44.png" />
    <Resource Include="assets\emoji\43.png" />
    <Resource Include="assets\emoji\42.png" />
    <Resource Include="assets\emoji\41.png" />
    <Resource Include="assets\emoji\40.png" />
    <Resource Include="views\wencaiwindow.baml" />
    <Resource Include="assets\data.png" />
    <Resource Include="assets\face\17.png" />
    <Resource Include="assets\face\16.png" />
    <Resource Include="assets\face\15.png" />
    <Resource Include="assets\face\14.png" />
    <Resource Include="assets\face\13.png" />
    <Resource Include="assets\face\12.png" />
    <Resource Include="assets\face\11.png" />
    <Resource Include="assets\face\10.png" />
    <Resource Include="assets\face\19.png" />
    <Resource Include="assets\face\18.png" />
    <Resource Include="assets\face\25.png" />
    <Resource Include="assets\face\24.png" />
    <Resource Include="assets\face\21.png" />
    <Resource Include="assets\face\23.png" />
    <Resource Include="assets\face\20.png" />
    <Resource Include="assets\face\22.png" />
    <Resource Include="assets\face\07.png" />
    <Resource Include="assets\face\05.png" />
    <Resource Include="assets\face\06.png" />
    <Resource Include="assets\face\03.png" />
    <Resource Include="assets\face\04.png" />
    <Resource Include="assets\face\01.png" />
    <Resource Include="assets\face\02.png" />
    <Resource Include="assets\face\09.png" />
    <Resource Include="assets\face\08.png" />
    <Resource Include="assets\app.ico" />
    <Resource Include="views\chartwindow.baml" />
    <Resource Include="views\exportcontrol.baml" />
    <Resource Include="views\livechartwindow.baml" />
    <Resource Include="views\stockview.baml" />
    <Resource Include="tv.js" />
    <Resource Include="views\importexportwindow.baml" />
    <Resource Include="views\positionwindow.baml" />
    <Resource Include="mainwindow.baml" />
    <Resource Include="views\proxywindow.baml" />
    <Resource Include="assets\emoji.png" />
    <Resource Include="views\sparrowwindow.baml" />
    <Resource Include="views\turtlewindowdc.baml" />
    <Resource Include="assets\pic.png" />
    <Resource Include="views\chatview.baml" />
    <Resource Include="views\sparrowwindowdc.baml" />
    <Resource Include="views\loginwindow.baml" />
    <Resource Include="app.baml" />
    <Resource Include="views\imageviewerwindow.baml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.28" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.9" />
  </ItemGroup>
</Project>

