<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>AIHelper</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>netcoreapp8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="assets\emoji_tab_icon.png" />
    <None Remove="assets\emoji\21.png" />
    <None Remove="assets\emoji\20.png" />
    <None Remove="assets\emoji\23.png" />
    <None Remove="assets\emoji\22.png" />
    <None Remove="assets\emoji\25.png" />
    <None Remove="assets\emoji\24.png" />
    <None Remove="assets\emoji\27.png" />
    <None Remove="assets\emoji\26.png" />
    <None Remove="assets\emoji\29.png" />
    <None Remove="assets\emoji\28.png" />
    <None Remove="assets\emoji\03.png" />
    <None Remove="assets\emoji\02.png" />
    <None Remove="assets\emoji\01.png" />
    <None Remove="assets\emoji\07.png" />
    <None Remove="assets\emoji\06.png" />
    <None Remove="assets\emoji\05.png" />
    <None Remove="assets\emoji\04.png" />
    <None Remove="assets\emoji\09.png" />
    <None Remove="assets\emoji\08.png" />
    <None Remove="assets\emoji\31.png" />
    <None Remove="assets\emoji\33.png" />
    <None Remove="assets\emoji\30.png" />
    <None Remove="assets\emoji\35.png" />
    <None Remove="assets\emoji\32.png" />
    <None Remove="assets\emoji\37.png" />
    <None Remove="assets\emoji\34.png" />
    <None Remove="assets\emoji\39.png" />
    <None Remove="assets\emoji\36.png" />
    <None Remove="assets\emoji\38.png" />
    <None Remove="assets\emoji\13.png" />
    <None Remove="assets\emoji\11.png" />
    <None Remove="assets\emoji\12.png" />
    <None Remove="assets\emoji\17.png" />
    <None Remove="assets\emoji\10.png" />
    <None Remove="assets\emoji\15.png" />
    <None Remove="assets\emoji\16.png" />
    <None Remove="assets\emoji\14.png" />
    <None Remove="assets\emoji\19.png" />
    <None Remove="assets\emoji\18.png" />
    <None Remove="assets\emoji\47.png" />
    <None Remove="assets\emoji\46.png" />
    <None Remove="assets\emoji\45.png" />
    <None Remove="assets\emoji\44.png" />
    <None Remove="assets\emoji\43.png" />
    <None Remove="assets\emoji\42.png" />
    <None Remove="assets\emoji\41.png" />
    <None Remove="assets\emoji\40.png" />
    <None Remove="views\wencaiwindow.baml" />
    <None Remove="assets\data.png" />
    <None Remove="assets\face\17.png" />
    <None Remove="assets\face\16.png" />
    <None Remove="assets\face\15.png" />
    <None Remove="assets\face\14.png" />
    <None Remove="assets\face\13.png" />
    <None Remove="assets\face\12.png" />
    <None Remove="assets\face\11.png" />
    <None Remove="assets\face\10.png" />
    <None Remove="assets\face\19.png" />
    <None Remove="assets\face\18.png" />
    <None Remove="assets\face\25.png" />
    <None Remove="assets\face\24.png" />
    <None Remove="assets\face\21.png" />
    <None Remove="assets\face\23.png" />
    <None Remove="assets\face\20.png" />
    <None Remove="assets\face\22.png" />
    <None Remove="assets\face\07.png" />
    <None Remove="assets\face\05.png" />
    <None Remove="assets\face\06.png" />
    <None Remove="assets\face\03.png" />
    <None Remove="assets\face\04.png" />
    <None Remove="assets\face\01.png" />
    <None Remove="assets\face\02.png" />
    <None Remove="assets\face\09.png" />
    <None Remove="assets\face\08.png" />
    <None Remove="assets\app.ico" />
    <None Remove="views\chartwindow.baml" />
    <None Remove="views\exportcontrol.baml" />
    <None Remove="views\livechartwindow.baml" />
    <None Remove="views\stockview.baml" />
    <None Remove="tv.js" />
    <None Remove="views\importexportwindow.baml" />
    <None Remove="views\positionwindow.baml" />
    <None Remove="mainwindow.baml" />
    <None Remove="views\proxywindow.baml" />
    <None Remove="assets\emoji.png" />
    <None Remove="views\sparrowwindow.baml" />
    <None Remove="views\datasourcewindow.baml" />
    <None Remove="views\turtlewindowdc.baml" />
    <None Remove="assets\pic.png" />
    <None Remove="views\chatview.baml" />
    <None Remove="views\sparrowwindowdc.baml" />
    <None Remove="views\loginwindow.baml" />
    <None Remove="app.baml" />
    <None Remove="views\imageviewerwindow.baml" />
    <EmbeddedResource Include="assets\emoji_tab_icon.png" />
    <EmbeddedResource Include="assets\emoji\21.png" />
    <EmbeddedResource Include="assets\emoji\20.png" />
    <EmbeddedResource Include="assets\emoji\23.png" />
    <EmbeddedResource Include="assets\emoji\22.png" />
    <EmbeddedResource Include="assets\emoji\25.png" />
    <EmbeddedResource Include="assets\emoji\24.png" />
    <EmbeddedResource Include="assets\emoji\27.png" />
    <EmbeddedResource Include="assets\emoji\26.png" />
    <EmbeddedResource Include="assets\emoji\29.png" />
    <EmbeddedResource Include="assets\emoji\28.png" />
    <EmbeddedResource Include="assets\emoji\03.png" />
    <EmbeddedResource Include="assets\emoji\02.png" />
    <EmbeddedResource Include="assets\emoji\01.png" />
    <EmbeddedResource Include="assets\emoji\07.png" />
    <EmbeddedResource Include="assets\emoji\06.png" />
    <EmbeddedResource Include="assets\emoji\05.png" />
    <EmbeddedResource Include="assets\emoji\04.png" />
    <EmbeddedResource Include="assets\emoji\09.png" />
    <EmbeddedResource Include="assets\emoji\08.png" />
    <EmbeddedResource Include="assets\emoji\31.png" />
    <EmbeddedResource Include="assets\emoji\33.png" />
    <EmbeddedResource Include="assets\emoji\30.png" />
    <EmbeddedResource Include="assets\emoji\35.png" />
    <EmbeddedResource Include="assets\emoji\32.png" />
    <EmbeddedResource Include="assets\emoji\37.png" />
    <EmbeddedResource Include="assets\emoji\34.png" />
    <EmbeddedResource Include="assets\emoji\39.png" />
    <EmbeddedResource Include="assets\emoji\36.png" />
    <EmbeddedResource Include="assets\emoji\38.png" />
    <EmbeddedResource Include="assets\emoji\13.png" />
    <EmbeddedResource Include="assets\emoji\11.png" />
    <EmbeddedResource Include="assets\emoji\12.png" />
    <EmbeddedResource Include="assets\emoji\17.png" />
    <EmbeddedResource Include="assets\emoji\10.png" />
    <EmbeddedResource Include="assets\emoji\15.png" />
    <EmbeddedResource Include="assets\emoji\16.png" />
    <EmbeddedResource Include="assets\emoji\14.png" />
    <EmbeddedResource Include="assets\emoji\19.png" />
    <EmbeddedResource Include="assets\emoji\18.png" />
    <EmbeddedResource Include="assets\emoji\47.png" />
    <EmbeddedResource Include="assets\emoji\46.png" />
    <EmbeddedResource Include="assets\emoji\45.png" />
    <EmbeddedResource Include="assets\emoji\44.png" />
    <EmbeddedResource Include="assets\emoji\43.png" />
    <EmbeddedResource Include="assets\emoji\42.png" />
    <EmbeddedResource Include="assets\emoji\41.png" />
    <EmbeddedResource Include="assets\emoji\40.png" />
    <EmbeddedResource Include="views\wencaiwindow.baml" />
    <EmbeddedResource Include="assets\data.png" />
    <EmbeddedResource Include="assets\face\17.png" />
    <EmbeddedResource Include="assets\face\16.png" />
    <EmbeddedResource Include="assets\face\15.png" />
    <EmbeddedResource Include="assets\face\14.png" />
    <EmbeddedResource Include="assets\face\13.png" />
    <EmbeddedResource Include="assets\face\12.png" />
    <EmbeddedResource Include="assets\face\11.png" />
    <EmbeddedResource Include="assets\face\10.png" />
    <EmbeddedResource Include="assets\face\19.png" />
    <EmbeddedResource Include="assets\face\18.png" />
    <EmbeddedResource Include="assets\face\25.png" />
    <EmbeddedResource Include="assets\face\24.png" />
    <EmbeddedResource Include="assets\face\21.png" />
    <EmbeddedResource Include="assets\face\23.png" />
    <EmbeddedResource Include="assets\face\20.png" />
    <EmbeddedResource Include="assets\face\22.png" />
    <EmbeddedResource Include="assets\face\07.png" />
    <EmbeddedResource Include="assets\face\05.png" />
    <EmbeddedResource Include="assets\face\06.png" />
    <EmbeddedResource Include="assets\face\03.png" />
    <EmbeddedResource Include="assets\face\04.png" />
    <EmbeddedResource Include="assets\face\01.png" />
    <EmbeddedResource Include="assets\face\02.png" />
    <EmbeddedResource Include="assets\face\09.png" />
    <EmbeddedResource Include="assets\face\08.png" />
    <EmbeddedResource Include="assets\app.ico" />
    <EmbeddedResource Include="views\chartwindow.baml" />
    <EmbeddedResource Include="views\exportcontrol.baml" />
    <EmbeddedResource Include="views\livechartwindow.baml" />
    <EmbeddedResource Include="views\stockview.baml" />
    <EmbeddedResource Include="tv.js" />
    <EmbeddedResource Include="views\importexportwindow.baml" />
    <EmbeddedResource Include="views\positionwindow.baml" />
    <EmbeddedResource Include="mainwindow.baml" />
    <EmbeddedResource Include="views\proxywindow.baml" />
    <EmbeddedResource Include="assets\emoji.png" />
    <EmbeddedResource Include="views\sparrowwindow.baml" />
    <EmbeddedResource Include="views\datasourcewindow.baml" />
    <EmbeddedResource Include="views\turtlewindowdc.baml" />
    <EmbeddedResource Include="assets\pic.png" />
    <EmbeddedResource Include="views\chatview.baml" />
    <EmbeddedResource Include="views\sparrowwindowdc.baml" />
    <EmbeddedResource Include="views\loginwindow.baml" />
    <EmbeddedResource Include="app.baml" />
    <EmbeddedResource Include="views\imageviewerwindow.baml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationCore">
      <HintPath>..\recovered-bundle\PresentationCore.dll</HintPath>
    </Reference>
    <Reference Include="WindowsBase">
      <HintPath>..\recovered-bundle\WindowsBase.dll</HintPath>
    </Reference>
    <Reference Include="HandyControl">
      <HintPath>..\recovered-bundle\HandyControl.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel">
      <HintPath>..\recovered-bundle\System.ComponentModel.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections">
      <HintPath>..\recovered-bundle\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Wpf">
      <HintPath>..\recovered-bundle\Microsoft.Web.WebView2.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>..\recovered-bundle\Microsoft.Web.WebView2.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.InteropServices">
      <HintPath>..\recovered-bundle\System.Runtime.InteropServices.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>..\recovered-bundle\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>..\recovered-bundle\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.WebProxy">
      <HintPath>..\recovered-bundle\System.Net.WebProxy.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Concurrent">
      <HintPath>..\recovered-bundle\System.Collections.Concurrent.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading">
      <HintPath>..\recovered-bundle\System.Threading.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq.Expressions">
      <HintPath>..\recovered-bundle\System.Linq.Expressions.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Primitives">
      <HintPath>..\recovered-bundle\System.Net.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography">
      <HintPath>..\recovered-bundle\System.Security.Cryptography.dll</HintPath>
    </Reference>
    <Reference Include="System.ObjectModel">
      <HintPath>..\recovered-bundle\System.ObjectModel.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.SignalR.Client.Core">
      <HintPath>..\recovered-bundle\Microsoft.AspNetCore.SignalR.Client.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Connections.Client">
      <HintPath>..\recovered-bundle\Microsoft.AspNetCore.Http.Connections.Client.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Ping">
      <HintPath>..\recovered-bundle\System.Net.Ping.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.RegularExpressions">
      <HintPath>..\recovered-bundle\System.Text.RegularExpressions.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.TypeConverter">
      <HintPath>..\recovered-bundle\System.ComponentModel.TypeConverter.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography.ProtectedData">
      <HintPath>..\recovered-bundle\System.Security.Cryptography.ProtectedData.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq">
      <HintPath>..\recovered-bundle\System.Linq.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.ServicePoint">
      <HintPath>..\recovered-bundle\System.Net.ServicePoint.dll</HintPath>
    </Reference>
    <Reference Include="System.Diagnostics.Process">
      <HintPath>..\recovered-bundle\System.Diagnostics.Process.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Encodings.Web">
      <HintPath>..\recovered-bundle\System.Text.Encodings.Web.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <HintPath>..\recovered-bundle\Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.SignalR.Client">
      <HintPath>..\recovered-bundle\Microsoft.AspNetCore.SignalR.Client.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>

